name: Commit lint

on:
  push:
    branches: [master, features]
  pull_request:
    branches: [master, features]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip comlipy
    - name: Check number of commits
      run: |
        n=$(git rev-list --count ^master HEAD)
        echo "$n commit(s) in the current branch."
        if [ $n -gt 1 ]; then
          echo "Your branch must contain only one commit. Please consider squashing them."
          exit 1
        fi
    - name: Lint
      run: |
        message="$(git log --format=%B -n 1 HEAD)"
        echo $message
        comlipy -c config-comlipy.yml "$message"

